In [1]:
from __future__ import print_function
import torch

In [2]:
x = torch.empty(5, 3)
print(x)

tensor([[-3.0556e+31,  6.7963e-43, -3.0557e+31],
        [ 6.7963e-43, -3.0560e+31,  6.7963e-43],
        [-3.0560e+31,  6.7963e-43, -3.0563e+31],
        [ 6.7963e-43, -3.0563e+31,  6.7963e-43],
        [-3.0559e+31,  6.7963e-43, -3.0559e+31]])


In [3]:
x = torch.rand(5, 3)
print(x)

tensor([[0.6327, 0.8749, 0.2137],
        [0.5607, 0.6574, 0.7439],
        [0.3545, 0.4012, 0.9667],
        [0.3244, 0.3982, 0.3204],
        [0.8314, 0.8624, 0.1371]])


In [4]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [5]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [6]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.7818,  0.1740, -1.5928],
        [ 0.6061, -0.3818, -0.1148],
        [-0.2751, -2.0602,  0.6329],
        [ 0.6826, -0.3795, -0.5745],
        [-1.9099, -0.4332, -0.0478]])


In [7]:
print(x.size())

torch.Size([5, 3])


In [8]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 1.7627,  0.4874, -1.0678],
        [ 1.1528,  0.2574, -0.0864],
        [ 0.2663, -1.1972,  0.7856],
        [ 1.0337,  0.3817,  0.1091],
        [-1.3780,  0.3386,  0.5314]])


In [9]:
print(x)
print(y)
print(torch.add(x, y))

tensor([[ 0.7818,  0.1740, -1.5928],
        [ 0.6061, -0.3818, -0.1148],
        [-0.2751, -2.0602,  0.6329],
        [ 0.6826, -0.3795, -0.5745],
        [-1.9099, -0.4332, -0.0478]])
tensor([[0.9809, 0.3134, 0.5250],
        [0.5466, 0.6392, 0.0284],
        [0.5414, 0.8630, 0.1527],
        [0.3511, 0.7612, 0.6836],
        [0.5319, 0.7718, 0.5793]])
tensor([[ 1.7627,  0.4874, -1.0678],
        [ 1.1528,  0.2574, -0.0864],
        [ 0.2663, -1.1972,  0.7856],
        [ 1.0337,  0.3817,  0.1091],
        [-1.3780,  0.3386,  0.5314]])


In [10]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 1.7627,  0.4874, -1.0678],
        [ 1.1528,  0.2574, -0.0864],
        [ 0.2663, -1.1972,  0.7856],
        [ 1.0337,  0.3817,  0.1091],
        [-1.3780,  0.3386,  0.5314]])


In [11]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 1.7627,  0.4874, -1.0678],
        [ 1.1528,  0.2574, -0.0864],
        [ 0.2663, -1.1972,  0.7856],
        [ 1.0337,  0.3817,  0.1091],
        [-1.3780,  0.3386,  0.5314]])


In [14]:
print(x)
print(x[:, 1]) #column @ 1
print(x[:, 0])

tensor([[ 0.7818,  0.1740, -1.5928],
        [ 0.6061, -0.3818, -0.1148],
        [-0.2751, -2.0602,  0.6329],
        [ 0.6826, -0.3795, -0.5745],
        [-1.9099, -0.4332, -0.0478]])
tensor([ 0.1740, -0.3818, -2.0602, -0.3795, -0.4332])
tensor([ 0.7818,  0.6061, -0.2751,  0.6826, -1.9099])


In [16]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8587])
-0.8586883544921875


In [18]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)
print(type(a))

tensor([1., 1., 1., 1., 1.])
<class 'torch.Tensor'>


In [19]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [20]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
# Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)
np.add(a, 1, out=a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [27]:
# CUDA Tensors
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
    print('CUDA Not Available')

CUDA Not Available
